name: My First Workflow

on:
  workflow_dispatch:
    inputs:
      test:
        description: "It's nice to see this description"
        required: true
      loglevel:
        description: "Log level"
        default: info
        type: choice
        options:
          - info
          - warning
          - debug
      testbuild:
        description: "It's a test build"
        required: true
        type: boolean
      environment:
        description: "Env to deploy"
        type: environment
        required: true
  repository_dispatch:
    types: ["coffee", "tea"]
        

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: List files
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "This repository ${{ github.repository }} contains the following files:"
          tree -a

      - name: Show inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |    
          echo "test input value: ${{ inputs.test }}"
          echo "loglevel input: ${{ inputs.loglevel }}"
          echo "testbuild input: ${{ inputs.testbuild }}"
          echo "environment input: ${{ inputs.environment }}"

      - name: Show payload
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo Payload: '${{ toJSON(github.event.client_payload) }}'

  MySecondJob:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}; sleep 30"
    
  MyThirdJob:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}; sleep 30"
      
  MyFourthJob:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}; sleep 30"

  MyFifthJob:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}; sleep 30"
